// Generated by scripts/generate-registries.ts. Do not edit.

import type { DocEntry } from "@/content/types/doc";

export const docs: DocEntry[] = [
  {
    slug: "avatar",
    title: "Avatar",
    description: "A user’s image, with initials as a fallback.",
    source: "packages/ui/src/components/avatar.tsx",
  },
  {
    slug: "button",
    title: "Button",
    description: "Triggers an action.",
    source: "packages/ui/src/components/button.tsx",
  },
  {
    slug: "input",
    title: "Input",
    description: "A single-line text field.",
    source: "packages/ui/src/components/input.tsx",
  },
  {
    slug: "loaders",
    title: "Loaders",
    description: "A set of 5×5 dot matrix loaders, each a self-contained SVG.",
    source: "packages/ui/src/components/dot-matrix",
  },
  {
    slug: "select",
    title: "Select",
    description: "Choose one or more values from a dropdown menu.",
    source: "packages/ui/src/components/select.tsx",
  },
  {
    slug: "textarea",
    title: "Textarea",
    description: "A multi-line text field.",
    source: "packages/ui/src/components/textarea.tsx",
  },
];
